### ISSUE TITLE
IRC messages not relaying to in-game chat (Bridge only)

### ISSUE THREAD

**Issue by djmixman** [Txuritan/devotion-irc#5]
Just as the topic says...

Everything seems to be setup correctly and I get the messages displayed on the server console, but they will not relay to in game chat.

**Comment by Txuritan** [comment]
What version are you using and are there any errors showing up on the log.

**Comment by djmixman** [comment]
Sorry I meant to get this and edit my original post but forgot.. The version I am running is: 

`eirairc-mc1.12.2-5.0.4.jar`

No errors are showing up in the log and everything seems to be working as designed. The bot will join the channel and relay messages from game to irc, but not from irc to game. IRC messages will show up in the log but not in the in-game chat. I am running server side only, the mod isn't in the client.

```
[05:22:32] [IRC (*****)/INFO] [net.blay09.mods.eirairc.irc.IRCConnectionImpl]: < :MiX-MaN!mix-man@hidden-tdm.hvu.6qm7j2.IP PRIVMSG #minecraft :test
[05:22:32] [IRC (*****)/INFO]: [#minecraft] <MiX-MaN> test
```

**Comment by Txuritan** [comment]
I'm thinking that the fix to solve the crash issue on server did break some things and doesn't have an Minecraft object to work off.

I'll look into this today and see if I can get it working, bridging was the one thing I didn't test.

**Comment by Txuritan** [comment]
So I've finally had the time to test it and yes it seams that the server doesn't send out IRC messages.

I am going to assume that it has to do with the changes that I've made to the internal chat system.

I'm not 100% sure on this but I'm thinking the problem is tied to one of the methods being use in the ```fireChannelChatEven``` [here](https://github.com/Txuritan/EiraIRC/blob/mc1122/src/main/java/net/blay09/mods/eirairc/handler/IRCEventHandler.java#L211).

**Comment by Txuritan** [comment]
I haven't tested it but the newest version (5.0.5) on CurseForge might have fixed the problem, I've managed to fix the Client/Server sendMessage Null crash which is where the fault would come from.

**Comment by djmixman** [comment]
Sorry for the delay in responding but it appears to may have fixed the issue. Thanks for your help! :)

**Comment by Txuritan** [comment]
So as it's turns out Forget has handlers for the Server and Client that I didn't know about and was trying to manually get the Server or Client instance, they solved most of the problem.
